name: Docker Build and Push

on:
  workflow_dispatch:
  push:
    branches:
      - main  # Change this to your main branch if different
    paths:
      - 'backend/**'
      - '.github/workflows/docker-build.yaml'

jobs:
  build-and-run:
    environment: Couillard
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker Image
      run: |
        docker compose build
        docker compose push
      working-directory: backend/

    
